---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/login":
    post:
      summary: create token and user admin
      tags:
      - auth
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  expires:
                    type: string
                  username:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
              required:
              - data
  "/api/v1":
    get:
      summary: Get words
      responses:
        '200':
          description: successful
        '400':
          description: bad request
  "/api/v1/words/search_synonyms":
    get:
      summary: List search_synonyms
      description: List synonyms
      parameters:
      - name: reference
        in: query
        description: word
        schema:
          type: string
      responses:
        '200':
          description: successful
        '400':
          description: bad request
  "/api/v1/words/create_synonym_and_word":
    parameters:
    - name: reference
      in: query
      description: word
      schema:
        type: string
    - name: synonym
      in: query
      description: synonym
      schema:
        type: string
    post:
      summary: create_synonym_and_word
      responses:
        '201':
          description: synonym and/or word created
        '422':
          description: invalid request
  "/api/v1/words/unreviewed_synonyms":
    get:
      summary: unreviewed_synonyms word
      responses:
        '200':
          description: successful
        '400':
          description: bad request
  "/api/v1/words/authorize_synonym":
    parameters:
    - name: reference
      in: query
      description: word
      schema:
        type: string
    - name: synonym
      in: query
      description: synonym
      schema:
        type: string
    put:
      summary: authorize_synonym word
      responses:
        '200':
          description: successful
        '400':
          description: bad request
  "/api/v1/words/delete_synonym":
    parameters:
    - name: reference
      in: query
      description: word
      schema:
        type: string
    - name: synonym
      in: query
      description: synonym
      schema:
        type: string
    delete:
      summary: delete_synonym word
      responses:
        '200':
          description: successful
        '400':
          description: bad request
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
