default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5432
  username: fernanda
  password: '961212fe'


development:
  <<: *default
  database: api_synonyms_db_development

test:
  <<: *default
  database: api_synonyms_db_test

production:
  <<: *default
  database: api_synonyms_db
  